# Generated by Django 3.1.3 on 2020-12-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentors',
            options={'verbose_name': 'Ментор', 'verbose_name_plural': 'Менторы'},
        ),
    ]
