# Generated by Django 3.1.3 on 2020-12-16 17:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20201216_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=33, verbose_name='Название команды')),
                ('referal_link', models.URLField(verbose_name='Реферальная ссылка')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Profile.mentordata')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TrainerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_vacation_start', models.DateField(blank=True, null=True, verbose_name='Дата начала отпуска')),
                ('date_of_vacation_duration', models.DurationField(blank=True, null=True, verbose_name='Длительность отпуска')),
                ('work_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Загрузка в часах')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='Profile.teamdata')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
            },
        ),
    ]
